name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Install dependencies
        run: npm i && cd client && npm i

      - name: Check style
        run: npm run lint

      - name: Create production build
        run: npm run build

      - name: Test code
        run: npm test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRETE: ${{ secrets.SECRETE }}

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3003
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
